Utiliza o endereço SSH ao invés do HTTPS no README
marqueslu/nerfherders pull request #3
Opened 2017-12-05 01:29 UTC by lidimayra

Lucão, tô abrindo um novo PR contendo exatamente as mesmas modificações do primeiro (e que foram revertidas)

Lembre-se que esse PR deve ser **revisado**. 

O meu PR tem como **única finalidade** alterar o endereço disponibilizado no readme de HTTPS para SSH.

Sua tarefa é verificar cada uma das alterações realizadas e apontar qualquer tipo de alteração que você ache que não faça sentido utilizando para isso o sistema de comentários do github.

Para facilitar a comunicação, procure sempre realizar o comentário selecionando a linha de código a que você se refere.

Fique à vontade para utilizar o mecanismo de comentários para falar qualquer coisa que quiser. Pode ser um pedido de correção, uma dúvida sobre o porquê algo ter sido feito, uma crítica, uma sugestão ou até mesmo um elogio haha

Ao terminar a revisão utilize o mecanismo de aprovação/pedido de mudanças/comentários conforme estão explicados na descrição da [Tarefa 4](https://github.com/lidimayra/treinamento-git/issues/4)_ (recomendo reler a tarefa para refrescar a memória)

Qualquer dúvida, só gritar! :heart:

2017-12-11 18:44 UTC, marqueslu requested changes

2017-12-11 18:44 UTC, marqueslu commented on README.md
> +- Este projeto principal objetivo o desenvolvimento de uma página para divulgação da equipe Nerfherders e seus respectivos projetos.
Aqui nessa linha ficou com um erro de conotação que pode dificultar o entendimento de quem vai ler.
Talvez **O principal objetivo deste projeto é....** ou **Este projeto tem como principal objetivo...**

2017-12-11 18:44 UTC, marqueslu commented on index.html
> -    <head>
Essa tag não pode ser removida pois faz parte do cabeçalho da página e também quando se remove uma _tag_ de abertura, é necessário remover a sua _tag_ de fachamento também.

2017-12-12 00:49 UTC, lidimayra commented on README.md
> +- Este projeto principal objetivo o desenvolvimento de uma página para divulgação da equipe Nerfherders e seus respectivos projetos.
oops! tem razão, isso nunca deveria ter sido alterado!

2017-12-12 00:51 UTC, lidimayra commented on index.html
> +        <h3>Nerfherders :)</h3>
isso aqui também não tinha relação com o meu PR, né?
se meu único objetivo era acrescentar o endereço ssh ao README, não tinha porque mudar aqui... aproveitarei as correções pra corrigir isso...

2017-12-12 00:54 UTC, lidimayra commented
As correções pedidas foram feitas @marqueslu!!
Aguardo no review :wink:

2017-12-13 10:54 UTC, marqueslu approved these changes

2017-12-13 10:54 UTC, merged

2017-12-13 10:56 UTC, marqueslu commented
Merge realizado com sucesso @lidimayra 😉